//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.13 at 04:03:48 PM CEST 
//


package com.michaelhitzker.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for chargeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chargeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="kwhCharged" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pricePerKwh" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="parkId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="stationId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chargeType", propOrder = {
    "startDate",
    "endDate",
    "duration",
    "kwhCharged",
    "pricePerKwh",
    "total",
    "userId",
    "parkId",
    "stationId"
})
@XmlRootElement(name = "charge")
public class ChargeType {

    protected long startDate;
    protected long endDate;
    protected double duration;
    protected double kwhCharged;
    protected double pricePerKwh;
    protected double total;
    protected long userId;
    protected long parkId;
    protected long stationId;

    /**
     * Gets the value of the startDate property.
     * 
     */
    public long getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     */
    public void setStartDate(long value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     */
    public long getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     */
    public void setEndDate(long value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     */
    public double getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(double value) {
        this.duration = value;
    }

    /**
     * Gets the value of the kwhCharged property.
     * 
     */
    public double getKwhCharged() {
        return kwhCharged;
    }

    /**
     * Sets the value of the kwhCharged property.
     * 
     */
    public void setKwhCharged(double value) {
        this.kwhCharged = value;
    }

    /**
     * Gets the value of the pricePerKwh property.
     * 
     */
    public double getPricePerKwh() {
        return pricePerKwh;
    }

    /**
     * Sets the value of the pricePerKwh property.
     * 
     */
    public void setPricePerKwh(double value) {
        this.pricePerKwh = value;
    }

    /**
     * Gets the value of the total property.
     * 
     */
    public double getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     */
    public void setTotal(double value) {
        this.total = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     */
    public long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(long value) {
        this.userId = value;
    }

    /**
     * Gets the value of the parkId property.
     * 
     */
    public long getParkId() {
        return parkId;
    }

    /**
     * Sets the value of the parkId property.
     * 
     */
    public void setParkId(long value) {
        this.parkId = value;
    }

    /**
     * Gets the value of the stationId property.
     * 
     */
    public long getStationId() {
        return stationId;
    }

    /**
     * Sets the value of the stationId property.
     * 
     */
    public void setStationId(long value) {
        this.stationId = value;
    }

}
