//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.13 at 04:03:48 PM CEST 
//


package com.michaelhitzker.data;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for chargingparkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chargingparkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="address" type="{http://www.emobility.org}addressType"/>
 *         &lt;element name="chargingstations" type="{http://www.emobility.org}chargingstationsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chargingparkType", propOrder = {
    "id",
    "address",
    "chargingstations"
})
@XmlRootElement(name = "chargingpark")
public class ChargingparkType {

    protected long id;
    @XmlElement(required = true)
    protected AddressType address;
    @XmlElement(required = true)
    protected ChargingstationsType chargingstations;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the chargingstations property.
     * 
     * @return
     *     possible object is
     *     {@link ChargingstationsType }
     *     
     */
    public ChargingstationsType getChargingstations() {
        return chargingstations;
    }

    /**
     * Sets the value of the chargingstations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargingstationsType }
     *     
     */
    public void setChargingstations(ChargingstationsType value) {
        this.chargingstations = value;
    }

}
