//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.13 at 04:03:48 PM CEST 
//


package com.michaelhitzker.data;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for chargingstationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chargingstationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="connector">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Type 1"/>
 *               &lt;enumeration value="Type 2"/>
 *               &lt;enumeration value="3-pin plug"/>
 *               &lt;enumeration value="CHAdeMO"/>
 *               &lt;enumeration value="Combined Charging System"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="maxPowerOut" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pricePerKwh" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="inUse" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chargingstationType", propOrder = {
    "id",
    "connector",
    "maxPowerOut",
    "pricePerKwh",
    "inUse"
})
@XmlRootElement(name = "chargingstation")
public class ChargingstationType {

    protected int id;
    @XmlElement(required = true)
    protected String connector;
    protected double maxPowerOut;
    protected double pricePerKwh;
    protected boolean inUse;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the connector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnector() {
        return connector;
    }

    /**
     * Sets the value of the connector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnector(String value) {
        this.connector = value;
    }

    /**
     * Gets the value of the maxPowerOut property.
     * 
     */
    public double getMaxPowerOut() {
        return maxPowerOut;
    }

    /**
     * Sets the value of the maxPowerOut property.
     * 
     */
    public void setMaxPowerOut(double value) {
        this.maxPowerOut = value;
    }

    /**
     * Gets the value of the pricePerKwh property.
     * 
     */
    public double getPricePerKwh() {
        return pricePerKwh;
    }

    /**
     * Sets the value of the pricePerKwh property.
     * 
     */
    public void setPricePerKwh(double value) {
        this.pricePerKwh = value;
    }

    /**
     * Gets the value of the inUse property.
     * 
     */
    public boolean isInUse() {
        return inUse;
    }

    /**
     * Sets the value of the inUse property.
     * 
     */
    public void setInUse(boolean value) {
        this.inUse = value;
    }

}
