//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.13 at 04:03:48 PM CEST 
//


package com.michaelhitzker.data;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for emobilityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="emobilityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="operator" type="{http://www.emobility.org}operatorType"/>
 *         &lt;element name="chargeManager" type="{http://www.emobility.org}chargeManagerType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "emobilityType", propOrder = {
    "operator",
    "chargeManager"
})@XmlRootElement(name = "emobility")

public class EmobilityType {

    @XmlElement(required = true)
    protected OperatorType operator;
    @XmlElement(required = true)
    protected ChargeManagerType chargeManager;

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link OperatorType }
     *     
     */
    public OperatorType getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatorType }
     *     
     */
    public void setOperator(OperatorType value) {
        this.operator = value;
    }

    /**
     * Gets the value of the chargeManager property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeManagerType }
     *     
     */
    public ChargeManagerType getChargeManager() {
        return chargeManager;
    }

    /**
     * Sets the value of the chargeManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeManagerType }
     *     
     */
    public void setChargeManager(ChargeManagerType value) {
        this.chargeManager = value;
    }

}
