//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.13 at 04:03:48 PM CEST 
//


package com.michaelhitzker.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for employeeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="employeeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.emobility.org}personType">
 *       &lt;sequence>
 *         &lt;element name="dateJoined" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="quitted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "employeeType", propOrder = {
    "dateJoined",
    "quitted",
    "discount"
})
@XmlRootElement(name = "employee")
public class EmployeeType
    extends PersonType
{

    protected long dateJoined;
    protected boolean quitted;
    protected double discount;

    /**
     * Gets the value of the dateJoined property.
     * 
     */
    public long getDateJoined() {
        return dateJoined;
    }

    /**
     * Sets the value of the dateJoined property.
     * 
     */
    public void setDateJoined(long value) {
        this.dateJoined = value;
    }

    /**
     * Gets the value of the quitted property.
     * 
     */
    public boolean isQuitted() {
        return quitted;
    }

    /**
     * Sets the value of the quitted property.
     * 
     */
    public void setQuitted(boolean value) {
        this.quitted = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     */
    public double getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     */
    public void setDiscount(double value) {
        this.discount = value;
    }

}
