//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.13 at 04:03:48 PM CEST 
//


package com.michaelhitzker.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.michaelhitzker.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Emobility_QNAME = new QName("http://www.emobility.org", "emobility");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.michaelhitzker.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmobilityType }
     * 
     */
    public EmobilityType createEmobilityType() {
        return new EmobilityType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link ChargeType }
     * 
     */
    public ChargeType createChargeType() {
        return new ChargeType();
    }

    /**
     * Create an instance of {@link ChargingparksType }
     * 
     */
    public ChargingparksType createChargingparksType() {
        return new ChargingparksType();
    }

    /**
     * Create an instance of {@link ChargesType }
     * 
     */
    public ChargesType createChargesType() {
        return new ChargesType();
    }

    /**
     * Create an instance of {@link EmployeeType }
     * 
     */
    public EmployeeType createEmployeeType() {
        return new EmployeeType();
    }

    /**
     * Create an instance of {@link ChargingparkType }
     * 
     */
    public ChargingparkType createChargingparkType() {
        return new ChargingparkType();
    }

    /**
     * Create an instance of {@link MembersType }
     * 
     */
    public MembersType createMembersType() {
        return new MembersType();
    }

    /**
     * Create an instance of {@link ChargeManagerType }
     * 
     */
    public ChargeManagerType createChargeManagerType() {
        return new ChargeManagerType();
    }

    /**
     * Create an instance of {@link ChargingstationType }
     * 
     */
    public ChargingstationType createChargingstationType() {
        return new ChargingstationType();
    }

    /**
     * Create an instance of {@link ChargingstationsType }
     * 
     */
    public ChargingstationsType createChargingstationsType() {
        return new ChargingstationsType();
    }

    /**
     * Create an instance of {@link MemberType }
     * 
     */
    public MemberType createMemberType() {
        return new MemberType();
    }

    /**
     * Create an instance of {@link EmployeesType }
     * 
     */
    public EmployeesType createEmployeesType() {
        return new EmployeesType();
    }

    /**
     * Create an instance of {@link OperatorType }
     * 
     */
    public OperatorType createOperatorType() {
        return new OperatorType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmobilityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.emobility.org", name = "emobility")
    public JAXBElement<EmobilityType> createEmobility(EmobilityType value) {
        return new JAXBElement<EmobilityType>(_Emobility_QNAME, EmobilityType.class, null, value);
    }

}
