//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.13 at 04:03:48 PM CEST 
//


package com.michaelhitzker.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for operatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="operatorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="chargingparks" type="{http://www.emobility.org}chargingparksType"/>
 *         &lt;element name="members" type="{http://www.emobility.org}membersType"/>
 *         &lt;element name="employees" type="{http://www.emobility.org}employeesType"/>
 *         &lt;element name="address" type="{http://www.emobility.org}addressType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "operatorType", propOrder = {
    "name",
    "email",
    "phone",
    "chargingparks",
    "members",
    "employees",
    "address"
})
public class OperatorType {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String email;
    protected long phone;
    @XmlElement(required = true)
    protected ChargingparksType chargingparks;
    @XmlElement(required = true)
    protected MembersType members;
    @XmlElement(required = true)
    protected EmployeesType employees;
    @XmlElement(required = true)
    protected AddressType address;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     */
    public long getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     */
    public void setPhone(long value) {
        this.phone = value;
    }

    /**
     * Gets the value of the chargingparks property.
     * 
     * @return
     *     possible object is
     *     {@link ChargingparksType }
     *     
     */
    public ChargingparksType getChargingparks() {
        return chargingparks;
    }

    /**
     * Sets the value of the chargingparks property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargingparksType }
     *     
     */
    public void setChargingparks(ChargingparksType value) {
        this.chargingparks = value;
    }

    /**
     * Gets the value of the members property.
     * 
     * @return
     *     possible object is
     *     {@link MembersType }
     *     
     */
    public MembersType getMembers() {
        return members;
    }

    /**
     * Sets the value of the members property.
     * 
     * @param value
     *     allowed object is
     *     {@link MembersType }
     *     
     */
    public void setMembers(MembersType value) {
        this.members = value;
    }

    /**
     * Gets the value of the employees property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeesType }
     *     
     */
    public EmployeesType getEmployees() {
        return employees;
    }

    /**
     * Sets the value of the employees property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeesType }
     *     
     */
    public void setEmployees(EmployeesType value) {
        this.employees = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

}
